language: python
python:
- '3.8'
install:
- pip install -r requirements.txt

addons:
  sonarcloud:
    organization: "hinakoushar-tatakoti"
    token: ${SONAR_TOKEN}

script:
 - python -m pytest -v src/unittest/python/books_tests.py
 - python -m pytest -v src/unittest/python/library_tests.py
 - sonar-scanner

notifications:
  email:
    - hinakoushar.tatakot@outlook.com
