language: python
python:
- '3.8'
install:
- pip install -r requirements.txt
script:
 - python src.main.python.users_tests.py
notifications:
  email:
    - hinakoushar.tatakot@outlook.com
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    repo: Hinakoushar-Tatakoti/Library-Management-System