language: python
python:
- '3.8'
install:
- pip install -r requirements.txt

addons:
  sonarcloud:
    organization: "hinakoushar-tatakoti"
    token:
      secure: "7951701ad328d9057a31250bc4ec8bf8acfe17de"

script:
 - python -m pytest -v src/unittest/python/books_tests.py
 - python -m pytest -v src/unittest/python/library_tests.py
 - sonar-scanner -X

notifications:
  email:
    - hinakoushar.tatakot@outlook.com
